-- ================================================================
-- TECNOCELL - SUPABASE DATABASE & STORAGE SCHEMA
-- ================================================================
-- Ejecuta este script completo en el SQL Editor de tu proyecto Supabase.

-- 1. CREACIÓN DE TABLA DE PRODUCTOS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    category TEXT NOT NULL DEFAULT 'pc', -- 'pc', 'tlf', 'belleza', o personalizada
    image_url TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. POLÍTICAS DE SEGURIDAD (RLS)
-- Los clientes públicos solo pueden ver productos activos
DROP POLICY IF EXISTS "Public can view active products" ON public.products;
CREATE POLICY "Public can view active products"
ON public.products
FOR SELECT
TO anon, authenticated
USING (is_active = true OR auth.role() = 'authenticated');

-- Los administradores autenticados pueden insertar, actualizar y borrar cualquier producto
DROP POLICY IF EXISTS "Admins have full access to products" ON public.products;
CREATE POLICY "Admins have full access to products"
ON public.products
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. CONFIGURAR STORAGE BUCKET PARA FOTOS
-- Crear el bucket 'product-images' si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage para 'product-images'
DROP POLICY IF EXISTS "Public can view product images" ON storage.objects;
CREATE POLICY "Public can view product images"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins can upload product images" ON storage.objects;
CREATE POLICY "Admins can upload product images"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins can update product images" ON storage.objects;
CREATE POLICY "Admins can update product images"
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins can delete product images" ON storage.objects;
CREATE POLICY "Admins can delete product images"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'product-images');

-- 5. SEED DATA (Productos Iniciales de TecnoCell)
INSERT INTO public.products (name, description, price, category, image_url, is_active, is_featured)
VALUES
    ('Mouse Gamer RGB X7', '12.000 DPI y 7 botones programables.', 25.00, 'pc', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/1f53228d6-250e-46ac-9ea2-14de26ec8199.png', true, false),
    ('Teclado Mecánico RGB K550', 'Switches mecánicos y rueda de volumen.', 48.00, 'pc', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/196a9ff00-34b6-45ad-84c8-142bfa32bc91.png', true, true),
    ('Headset Gamer Pro H2', 'Sonido envolvente y micro flexible.', 32.00, 'pc', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/1bba8861c-1ee8-4326-9ada-4f14a96ac994.png', true, false),
    ('Webcam Full HD 1080p', 'Con micrófono integrado.', 27.00, 'pc', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/19e60117a-b5e9-45fb-bb9a-9c00cfd2a142.png', true, false),
    ('Cargador Rápido 25W USB‑C', 'Carga rápida PD multimarca.', 15.00, 'tlf', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/1f1634d8e-9c80-463e-b685-361b7114b879.png', true, true),
    ('Cable Trenzado USB‑C 2 m', 'Nylon reforzado y conectores de aluminio.', 8.00, 'tlf', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/102702188-0d43-46fa-9b2b-de888ac7db64.png', true, false),
    ('Power Bank 10.000 mAh', 'Doble salida con pantalla digital.', 22.00, 'tlf', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/15d36eeab-196d-4673-98ff-9fb25f94a230.png', true, false),
    ('Earbuds Bluetooth TWS', 'Control táctil y estuche de carga.', 18.00, 'tlf', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/1ccaad71a-947d-4d26-84e6-8cc209c288b5.png', true, false),
    ('Deep Vita C Capsule Cream', 'Vitamina C + Niacinamida 5% · 55 g.', 35.00, 'belleza', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/116f6a03c-819a-41b6-aa3b-946b214a318f.png', true, false),
    ('Ácido Azelaico 10%', 'Fórmula iluminadora · 30 ml.', 20.00, 'belleza', 'https://image.qwenlm.ai/public_source/1310e334-0345-45b6-afbb-14b1c138cbad/1250c8c9f-9605-443b-821b-f454cb109948.png', true, false)
ON CONFLICT DO NOTHING;
