-- ================================================================
-- TECNOCELL - SUPABASE DATABASE & STORAGE SCHEMA
-- ================================================================
-- Ejecuta este script completo en el SQL Editor de tu proyecto Supabase.

-- 1. CREACIÓN DE TABLA DE PRODUCTOS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    category TEXT NOT NULL DEFAULT 'pc', -- 'pc', 'tlf', 'belleza', o personalizada
    image_url TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. POLÍTICAS DE SEGURIDAD (RLS)
-- Los clientes públicos solo pueden ver productos activos
DROP POLICY IF EXISTS "Public can view active products" ON public.products;
CREATE POLICY "Public can view active products"
ON public.products
FOR SELECT
TO anon, authenticated
USING (is_active = true OR auth.role() = 'authenticated');

-- Los administradores autenticados pueden insertar, actualizar y borrar cualquier producto
-- Los administradores autorizados pueden insertar, actualizar y borrar productos
-- IMPORTANTE: Configura aquí el correo de tu cuenta administradora de Supabase
DROP POLICY IF EXISTS "Admins have full access to products" ON public.products;
CREATE POLICY "Admins have full access to products"
ON public.products
FOR ALL
TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@tecnocell.com')
WITH CHECK (auth.jwt() ->> 'email' = 'admin@tecnocell.com');

-- 4. CONFIGURAR STORAGE BUCKET PARA FOTOS
-- Crear el bucket 'product-images' si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage para 'product-images'
DROP POLICY IF EXISTS "Public can view product images" ON storage.objects;
CREATE POLICY "Public can view product images"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins can upload product images" ON storage.objects;
CREATE POLICY "Admins can upload product images"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins can update product images" ON storage.objects;
CREATE POLICY "Admins can update product images"
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins can delete product images" ON storage.objects;
CREATE POLICY "Admins can delete product images"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'product-images');

-- 5. SEED DATA (Productos Iniciales de TecnoCell)
INSERT INTO public.products (name, description, price, category, image_url, is_active, is_featured)
VALUES
    ('Cargador Completo 20W (Cubo + Cable)', 'Kit de carga rápida con adaptador USB-C de 20W y cable de alta velocidad. Carga hasta un 50% de batería en 30 minutos.', 25.00, 'cargadores', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MHJA3?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, true),
    ('Cargador Completo Dual USB-C 35W + Cable', 'Adaptador de corriente compacto con doble puerto USB-C de 35W y cable reforzado. Carga dos dispositivos en simultáneo.', 45.00, 'cargadores', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MNWM3?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Cargador Rápido 50W Doble Puerto GaN', 'Potente cargador ultrarrápido de 50W con tecnología GaN y dos salidas inteligentes (USB-C + USB-A) para laptops y celulares.', 35.00, 'cargadores', 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1000&q=80', true, false),
    ('Cable USB-A a USB-C Alta Resistencia', 'Cable de carga y sincronización ultrarresistente con conectores reforzados antidoblado y recubrimiento duradero.', 8.00, 'cargadores', 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=1000&q=80', true, false),
    ('Cable USB-A a Lightning Clásico (1 m)', 'Cable de 1 metro para conexión y sincronización estable de iPhone, iPad y estuches de AirPods.', 12.00, 'cargadores', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MXLY2?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Cable USB-C a USB-C Trenzado 60W (1 m)', 'Cable con recubrimiento de tejido trenzado. Compatible con Power Delivery de 60W para carga ultra rápida.', 19.00, 'cargadores', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQKJ3?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Apple AirPods (2.ª Generación)', 'Auriculares inalámbricos con chip H1 de conexión veloz, activación por voz con Siri y más de 24 horas de autonomía.', 99.00, 'audio', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV7N2?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, true),
    ('Apple AirPods (3.ª Generación)', 'Audio espacial con seguimiento dinámico de la cabeza, ecualización adaptativa, resistencia IPX4 y estuche MagSafe.', 149.00, 'audio', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Apple AirPods Max', 'Auriculares over-ear de alta fidelidad con cancelación activa de ruido profesional, modo ambiente y almohadillas acústicas.', 499.00, 'audio', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-spacegray-202011?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, true),
    ('Apple Watch Series 10', 'Diseño ultradelgado con pantalla OLED de amplio ángulo, monitor de ECG, oxígeno en sangre y carga rápida magnética.', 399.00, 'watch', 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1000&q=80', true, false),
    ('Apple Watch Ultra 2', 'Smartwatch premium con caja de titanio aeroespacial de 49 mm, pantalla de 3000 nits, GPS dual y batería de hasta 72h.', 799.00, 'watch', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=80', true, true),
    ('Apple MagSafe Battery Pack', 'Batería portátil magnética inalámbrica que se acopla a la perfección a tu iPhone para proporcionar carga automática y segura.', 89.00, 'magsafe', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJWY3?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Power Bank Magnético MagSafe Pro con Soporte', 'Batería inalámbrica magnética de 10.000 mAh con pata de apoyo abatible integrada, imanes fuertes y puerto USB-C bidireccional.', 39.00, 'magsafe', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJWY3_AV2?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Billetera MagSafe de Cuero para iPhone', 'Tarjetero de cuero genuino con potentes imanes integrados, protección electromagnética y compatibilidad con la red Buscar.', 35.00, 'magsafe', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MM0Y3?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false),
    ('Billetera MagSafe FineWoven para iPhone', 'Tarjetero magnético en microtwill ecológico FineWoven de tacto suave. Capacidad para 3 tarjetas y soporte Find My.', 29.00, 'magsafe', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT243?wid=1000&hei=1000&fmt=jpeg&qlt=95', true, false)
ON CONFLICT DO NOTHING;
